// // const swaggerAutogen = require('swagger-autogen')();

// // const outputFile = './swagger-output.json'; // generated Swagger file
// // const endpointsFiles = ['./app.js']; // your main Express file(s)

// // const doc = {
// //   info: {
// //     title: 'My API',
// //     description: 'API autogenerated by swagger-autogen',
// //   },
// //   host: 'localhost:3000',
// //   schemes: ['http'],
// // };

// // swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
// //   console.log('Swagger documentation generated successfully!');
// // });
// const swaggerFile = require('./swagger-output.json');
// const swaggerAutogen = require('swagger-autogen')();

// const outputFile = './swagger-output.json'; // This is the file your app.js is trying to require
// const endpointsFiles = ['./app.js'];        // Scan your main app file (or route files) for routes

// const doc = {
//   info: {
//     title: 'Auth Service API',
//     description: 'Auto-generated Swagger documentation for Auth Service',
//   },
//   host: 'localhost:3000',
//   schemes: ['http'],
// };

// swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
//   console.log('Swagger documentation generated successfully!');
// });

